export default {
    ABOUT_HEADING: 'Salut! Je me nomme Pape Moussa,\n Je suis informaticien en cours de formation à lUniversité Amadou Mahtar Mbow de Diamniadio.',
    ABOUT_DESC: 'Je suis surtout trés passioné du Web Design et avec une forte curiosité en la matière. Je suis en ma troisième année de licence d\'ingénieurie informatique à l\'Université Amadou Mahtar Mbow de Diamniadio.',

    SERVICES: 'SERVICES',
    FRONTEND: 'FRONTEND DEV',
    FRONTEND_DESC: 'Rendre votre présence en ligne plus conviviale avec des interfaces et expériences trés captivants.',

    EDUCATION: 'EDUCATION',
    ETAB1: 'ECOLE ELEMENTAIRE DE DIOKOUL',
    AN1: '2007-2013',
    DIPLOME1: 'Certificat de Fin d\'Etudes Elémentaires',

    ETAB2: 'CEM NDIEYENE SIRAKH',
    AN2: '2013-2017',
    DIPLOME2: 'Brevet de Fin d\'Etudes Moyennes',

    ETAB3: 'LYCEE EL-HADJI MALICK SY DE THIES',
    AN3: '2017-2020',
    DIPLOME3: 'Baccalauréat Scientifique',

    ETAB4: 'UNIVERSITE AMADOU MAHTAR MBOW DE DIAMNIADIO',
    AN4: '2020-2023',
    DIPLOME4: 'Licence Ingénieurie Informatique',

    INFO: 'INFORMATIONS PERSONELLES',
    PRENOM: 'PAPE MOUSSA',
    NOM: 'DIOP',
    ADDPHYSIQUE1: 'Diokoul/Khombole/Thiès',
    ADDPHYSIQUE2: 'Grand Standing/Thiès',
    ADDEMAIL1: 'joob.18.12@gmail.com',
    ADDEMAIL2: 'diop.moussa@uam.edu.sn',
    TEL1: '784641763',
    TEL2: '704930131',

    COMPETENCES: "COMPETENCES",
    LANGAGES: "Langages de programmation",
    LANGAGESDESC: "Au cours de ma formation à l'université, j'ai eu l'occasion de voir plusieurs langages de programmation dont :",
    DEVWEB: "Développement Web",
    DEVWEBDESC: "Développement Web",
    DEVLOGICIEL: " Développement Logiciel",
    DEVLOGICIELDESC: " Développement Logiciel",
    DESIGN: " UX/UI Design",
    DESIGNDESC: " UX/UI Design",
    GRAPHISME: "Graphisme",
    GRAPHISMEDESC: "Graphisme",
    INFOGRAPHIE: "Infographie",
    INFOGRAPHIEDESC: "Infographie",
    PHOTOGRAPHIE: "Photographie",
    PHOTOGRAPHIEDESC: "Photographie",
    REPARATION: "Maintenance-Réparation",
    REPARATIONDESC: "Maintenance-Réparation",
    DESSIN: "Dessin",
    DESSINDESC: "Dessin",
    PROD: "Production musicale",
    PRODDESC: "Production musicale",
    RESOL: "Résolution de problèmes",
    RESOLDESC: "Résolution de problèmes",
    GESTION: "Gestion",
    GESTIONDESC: "Gestion",
    RECHERCHE: "Recherche Documentaire",
    RECHERCHEDESC: "Recherche Documentaire",

}